---

- name: apply kubernetes manifests 
  hosts: bottle1
  tasks:

  - name: copy out dragon-network.yml to bottle1
    copy:
      src: files/dragon-network.yml
      dest: /root/dragon-network.yml

  - name: apply network manifest
    shell: k3s kubectl apply -f /root/dragon-network.yml
    args:
      executable: /bin/bash

  - name: re apply firewalld
    zypper:
      name: firewalld
      state: installed

  - name: restart firewalld
    shell: systemctl enable firewalld && systemctl restart firewalld
    args:
      executable: /bin/bash

- name: hatch egg 
  hosts: bottle2
  tasks:

  - name: disable firewalld on bottle2 nodes
    shell: systemctl disable firewalld && systemctl stop firewalld
    args:
      executable: /bin/bash


...
