---

- name: make bottles
  hosts: bottles
  tasks:

  - name: install auditd
    zypper:
      name: audit
      state: present
 
  - name: install apparmor
    zypper:
      name: apparmor
      state: present
 
  - name: install vim
    zypper:
      name: vim
      state: present
     
  - name: install tcpdmp
    zypper:
      name: tcpdump
      state: present
  
  - name: install git
    zypper:
      name: git
      state: present
  
  - name: install openssl
    zypper:
      name: git
      state: present
  
  - name: install curl
    zypper:
      name: curl
      state: present
 
  - name: remove firewalld
    shell: systemctl stop firewalld && systemctl disable firewalld
    args:
      executable: /bin/bash

  - name: remove firewalld
    zypper:
      name: firewalld
      state: removed
 
  - name: set motd
    copy:
      src: files/motd
      dest: /etc/motd
    tags: motd

...
