---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-rules
spec:
  selector: "all()"
  order: 0
  ingress:
  - action: Allow
    protocol: TCP
    source:
      nets:
        - "192.168.1.0/24"
        - "10.0.0.0/8"
        - "172.16.0.0/12"
  - action: Allow
    protocol: UDP
    source:
      nets:
        - "192.168.1.0/24"
        - "10.0.0.0/8"
        - "172.16.0.0/12"
  - action: Allow
    protocol: ICMP
  egress:
  - action: Allow
    protocol: TCP
  - action: Allow
    protocol: UDP

---
