---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-rules
spec:
  selector: "all()"
  order: 0
  ingress:
  - action: Allow
    protocol: TCP
    source:
      nets:
        - "192.168.1.0/24"
    destination:
      ports: 
        - 22
        - 1514
        - 1515
        - 30311
  - action: Allow
    protocol: ICMP
  egress:
  - action: Allow
    protocol: TCP
    destination:
      nets:
        - "192.168.1.0/24"
      ports:
        - 514
        - 1514
        - 1515
  - action: Allow
    protocol: UDP
    destination:
      ports: 
        - 67
        - 1515
        - 1514
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  order: 1
  selector: projectcalico.org/namespace != "kube-system|dragon"
  types:
  - Ingress
  - Egress
...
